# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parking
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Database'

  target 'ParkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
